site_name: Docker Tutorial - Part 2
repo_url: https://github.com/spigad/docker-tutorial
site_author: Daniele Spiga - daniele.spiga@pg.infn.it
theme:
  name: material
  palette:
    primary: teal
    accent: green
  logo: assets/logo_infn.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
   
nav:
  - Building images interactively : 
    - First step: 'intro/index.md'
  - Building docker images with Dockerfiles:
    - First step: 'intro/index.md'

copyright: Copyright &copy; 2021 INFN
