site_name: Docker Tutorial - Part 2
repo_url: https://github.com/spigad/docker-tutorial
site_author: Daniele Spiga - daniele.spiga@pg.infn.it
theme:
  name: material
  palette:
    primary: teal
    accent: green
  logo: assets/logo_infn.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
   
nav:
  - Introduction: 
    - Building images interactively: 'intro/index.md'
  - Dockerfiles: 
    - Write the first Dockerfile: 'dockerfile/first-dockrefile.md'
    - The CMD and ENTRYPOINT verbs: 'dockerfile/cmd-entrypoint.md'
    - Copying files during the build: 'dockerfile/copy.md'
    - Additional commands: 'dockerfile/more-commands.md'
    - Exercise: 'dockerfile/exercise.md'  
  - Cache and dangling images: 
    - What are <none> tags: 'cacheimaegs/cache-dangling.md'
  - Docker Registry: 
    - Publishing images to the Docker hub: 'registry/dockerhub.md'


Credits: the material had many contributors among which Jérôme Petazzoni; 2021 INFN
